name = "mfc2_raw_dia"
version = "0.1.0"
license = "license"
author = "Patrizia Favaron"
maintainer = "patti.favaron@gmail.com"
copyright = "Copyright 2026, Patrizia Favaron"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

